<<<<<<< HEAD:.github/workflows/ci.yml
name: CI
=======
name: Lint Check
>>>>>>> refs/remotes/origin/main:.github/workflows/main.yml

on: push

jobs:
<<<<<<< HEAD:.github/workflows/ci.yml
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
=======
  lint:
    name: lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
        
      - name: Run super-linter
        uses: github/super-linter@v3
>>>>>>> refs/remotes/origin/main:.github/workflows/main.yml
