name: Node.js Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2' # Use the latest available Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
