name: Lint Check

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code base
        uses: actions/checkout@v3

      - name: Run super-linter
        uses: github/super-linter@v3
