name: ESLint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2' # Use the Node.js version you prefer

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint # Adjust this command based on your ESLint setup
