name: Lint Check

on: push

jobs:
  lint:
    name: lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
        
      - name: Run super-linter
        uses: github/super-linter@v3
